name: mudolist
services:
  mudolist:
    container_name: mudolist
    image: ghcr.io/tserath/mudolist:latest
    ports:
      - "5000:5000"
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongo:27017/mudolist
      - PORT=5000
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=F6ecggS1IKjkHVDZr/ahwOvR21q/9N4ILAhDKnNS+6U=
    depends_on:
      - mongo
    command: ["/app/start.sh"]

  mongo:
    container_name: mudolist-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
