services:
  frontend:
    container_name: mudolist-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend

  backend:
    container_name: mudolist-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Need this for browser access
    expose:
      - "5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mudolist
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
    depends_on:
      - mongodb

  mongodb:
    container_name: mudolist-mongodb
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=mudolist

volumes:
  mongodb_data:
    name: mudolist-mongodb-data
  mongodb_config:
    name: mudolist-mongodb-config
