services:
  frontend:
    container_name: mudolist-frontend
    image: ghcr.io/tserath/mudolist/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mudolist.rule=Host(`mudolist.${DOMAIN}`)"
      - "traefik.http.routers.mudolist.entrypoints=websecure"
      - "traefik.http.routers.mudolist.tls=true"
      - "traefik.http.routers.mudolist.middlewares=authelia@docker"
      - "traefik.http.services.mudolist.loadbalancer.server.port=5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_API_URL=https://api.mudolist.${DOMAIN}
    depends_on:
      - backend

  backend:
    container_name: mudolist-backend
    image: ghcr.io/tserath/mudolist/backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Need this for browser access
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mudolist-api.rule=Host(`api.mudolist.${DOMAIN}`)"
      - "traefik.http.routers.mudolist-api.entrypoints=websecure"
      - "traefik.http.routers.mudolist-api.tls=true"
      - "traefik.http.routers.mudolist-api.middlewares=authelia@docker"
      - "traefik.http.services.mudolist-api.loadbalancer.server.port=5000"
    expose:
      - "5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mudolist
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
      - CORS_ORIGIN=https://mudolist.${DOMAIN}
    depends_on:
      - mongodb

  mongodb:
    container_name: mudolist-mongodb
    image: mongo:latest
    networks:
      - proxy
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=mudolist

volumes:
  mongodb_data:
    name: mudolist-mongodb-data
  mongodb_config:
    name: mudolist-mongodb-config

networks:
  proxy:
    external: true
    name: proxy
